spring:
  application:
    name: oms

  datasource:
    url: jdbc:mysql://localhost:3306/oms
    username: 설정하세요!
    password: 설정하세요!
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8.x ??? ?? ????? ??

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

base_url: "http://localhost:8080"